### ISSUE TITLE
Learning to use git from command line

### ISSUE THREAD

**Issue by AmberFennek** [Pinacolada64/NOW#2]
1. Tria's updated the server/conf/settings.py on the server and needs to know how to submit the change to the main repository.  I could just drag and drop the new file in, but then you would need me to update things all the time. 
1. Add "Tricuspa" as a contributor to allow wiki editing. ✓

**Comment by Pinacolada64** [comment]
Okay! @tricuspa has been added. (command line github lesson should be a separate issue to reduce confusion)

**Comment by Pinacolada64** [comment]
@tricuspa
Do you have a git client installed? (The way I do it is with "sudo apt-get install git", your Linux distribution may be different.)

Here is a basic tutorial on how to set up git from the command line: https://help.github.com/articles/set-up-git/

**Comment by AmberFennek** [comment]
I'm certain Tria has git installed - because I installed it to pull Evennia.

Tria also mentioned installing the GUI. I think the only thing left is to walk-through updating the NOW folder to the repository.

**Comment by Pinacolada64** [comment]
Here's a tutorial: http://rogerdudler.github.io/git-guide/

**Comment by AmberFennek** [comment]
Yay! Tutorial link!  I will read this and become smart and wise.

**Comment by AmberFennek** [comment]
Tutorial was not much help. git is making me sad.
Sorry if I keep breaking things.  I am trying, but I need more help.

The two files in our source that we have changed, I could not pull, so I just uploaded them manually with wget. Is there no good resource for explaining how to use git, or is it just that complicated?

**Comment by Pinacolada64** [comment]
It's okay to break stuff. *sigh* I think git is just that complicated.

**Comment by AmberFennek** [comment]
The git book and the video on YouTube that Tria mentioned (but did not post here) were helpful.

**Comment by Pinacolada64** [comment]
Please post the links!

**Comment by AmberFennek** [comment]
http://youtu.be/Y9XZQO1n_7c
http://youtu.be/0fKg7e37bQE
https://git-scm.com/book/en/v2

**Comment by Pinacolada64** [comment]
@AmberFennek Here is another (interactive) tutorial I learned about today. https://try.github.io/levels/1/challenges/1

**Comment by AmberFennek** [comment]
I found that one to be confusing, in so much as it expects people to press the button instead of type the  response. When I typed the response and got "success" it did not count to moving the tutorial forward, so was very confusing that some of the tutorial was marked as being completed while other parts were not.

Additionally, it does not cover "real world" use, which is the problem I face when I actually go to use a thing to discover that my use case has no instructive material or help.  A good example is when I branched my changes, then submitted them, then found that they could not be merged to the master branch in github. I ended up just deleting the branch and using the web interface to commit the file directly to master branch via upload, after downloading the edited file from the server, then uploading it into the repository.

But honestly, my motivation has been diminished by other factors, too.  The most basic one is being told to "take a break" because I am apparently bothering potential contributors by trying to interact with them to accomplish goals.

**Comment by AmberFennek** [comment]
What works really well is installing git, but using PyCharm's interface to manage it.
Once the work flow is understood, the command line is not mysterious.

Additionally, once the structure of the project files is more organized, it helps streamline the process, too.  Thanks to @Pinacolada64 !

**Comment by AmberFennek** [comment]
@tricuspa  Using this document as a reference, because it is the best overview on the subject found to date: https://backlogtool.com/git-guide/en/intro/intro1_1.html

**Comment by Pinacolada64** [comment]
Hey, I really like that tutorial. Good find, @AmberFennek :+1:
