### ISSUE TITLE
Bug report: Command 'pub' is not available. Maybe you meant "pub" or "up" ?

### ISSUE THREAD

**Issue by dimaguy** [Pinacolada64/NOW#25]
I joined NOW today, and I noticed when I typed the command 'pub' (for curiosity really, I didnt believe it would work), and shows up the message:

> Command 'pub' is not available. Maybe you meant "pub" or "up" ?

Now I dont think pub is really a command, are commands and places mixed up in the tips?

**Comment by tricuspa** [comment]
**pub** is not a "command" as much as the Public broadcast Channel, it should be working as expected now.

**Comment by tricuspa** [comment]
PUB works properly at this point.
