### ISSUE TITLE
Show which characters are active from the web page

### ISSUE THREAD

**Issue by tricuspa** [Pinacolada64/NOW#3]
It would be more helpful to have a WHO that either queries once or a running board to show who is connected.

**Comment by AmberFennek** [comment]
I added it to https://github.com/Pinacolada64/NOW/wiki/todo

Rulan should talk to LazyLion about becoming a contributor. Because he mentioned wanting to work on web things for NOW.

**Comment by Pinacolada64** [comment]
Lazylion is welcome to join, I'll ask him the next time I see him.

**Comment by AmberFennek** [comment]
Tria also mentions it on https://github.com/Pinacolada64/NOW/wiki/commands  (currently a command we want, not a command we have.)

**Comment by Pinacolada64** [comment]
Oh, okay.

**Comment by AmberFennek** [comment]
* Autonomy – the urge to direct our own lives.
* Mastery – the desire to get better and better at something that matters.
* Purpose – the yearning to do what we do in the service of something larger than ourselves.

**Comment by AmberFennek** [comment]
This is mostly complete, but not quite done properly, so I will leave it open for now even though we have a functional solution working.

**Comment by AmberFennek** [comment]
The proper way to do this is documented [here:]( https://github.com/evennia/evennia/wiki/Web-Features#overloading-django-views) and requires overloading with a custom views.py, which means defining a variable composed of a list of current online characters and perhaps idle times, then modifying the index.html to support the display in HTML.  Anyone interested can contribute - and possibly expand this feature to realm-wide WHO lists and present realms via web with additional information in them gathered from the in-game realmentry rooms.

**Comment by AmberFennek** [comment]
Until there's a solution, the work-around is to update `evennia/web/website/views.py` every time Evennia updates it.  Because the proper way may or may not work in this case, we either need someone who understands how this is done or if it does not work, someone needs to inquire with the contributors as to how it can best be changed to be done.   See the link in the last post above.

**Comment by Pinacolada64** [comment]
Web-based listing of players seems to work. Yay @AmberFennek :smile:
