### ISSUE TITLE
Notify the player when joining a character of character's current RP setting

### ISSUE THREAD

**Issue by AmberFennek** [Pinacolada64/NOW#7]
On joining the character, in addition to the "You assume the role of..." message, giving the RP status is a good idea.

* Tria flutes, "It may be wise to note the player when they login in their current RP"

**Comment by tricuspa** [comment]
Looks good, sentence structure appears in RP when folks use it so they see what they will look like. At this point I think we've got it covered, perhaps next step is a toggle switch that either resets pose when moving or leaves it as is.

**Comment by AmberFennek** [comment]
@tricuspa There is a default doing message (RP) versus the current doing message, similar to FM's "sticky" and "temp" doing messages, where the temp message resets when moving.  But setting the default seems to not work as expected yet.

Also, the message will automatically change when sitting on an item such as furniture and hopefully revert to the room pose when leaving it, since the character never leaves the room in that case.

I just have not thought through how all the details are expected to work.  Feel free to discuss them here and I will add the changes or get @JeeDRGN or @Pinacolada64 to do it if it is not too involved.  If it is flexible and helpful, the feature will get more use.  It is also somewhat helpful as a sort of "away" message in some cases, giving the character a reason for being idle.
